// GLSL Vertex Shader "main"
// Generated by XShaderCompiler
// 17/02/2017 17:01:54

#version 140

in vec4 Pos;
in vec2 Tex;
in vec3 Nor;
in vec4 Col;

out vec2 xsc_vary_TEXCOORD0;
out vec3 xsc_vary_NORMAL;
out vec4 xsc_vary_COLOR;

layout(std140) uniform PerObject
{
    mat4 world;
};

layout(std140) uniform OnResize
{
    mat4 projection;
};

layout(std140) uniform NeverChanges
{
    mat4 view;
};

void main()
{
    gl_Position = (Pos * world);
    gl_Position = (gl_Position * view);
    gl_Position = (gl_Position * projection);
    xsc_vary_TEXCOORD0 = Tex;
    xsc_vary_NORMAL = Nor;
    xsc_vary_COLOR = Col;
}

